
auth.token=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

defaults.org=second-round-inc
defaults.project=react-native

defaults.url=https://sentry.io/
